
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    volumes:
      - .:/app  # Mount current directory to /app in the container
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:password@db:5432/netology_stocks_products  # Adjust as needed
    depends_on:
      - db  # Ensure the database starts before Django
    networks:
      - mynetwork

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    environment:
      POSTGRES_DB: netology_stocks_products  # Name of the database
      POSTGRES_USER: postgres  # Default PostgreSQL user
      POSTGRES_PASSWORD: password  # Set a secure password for production use!
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data between container restarts
    networks:
      - mynetwork

  nginx:
    image: nginx:latest  # Use the latest Nginx image
    ports:
      - "80:80"  # Map port 80 on the host to port 80 on the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Ensure you have an nginx.conf file in your project directory
    depends_on:
      - backend  # Ensure Nginx starts after Django
    networks:
      - mynetwork

networks:
  mynetwork:  # Define a custom network for communication between containers

volumes:
  pgdata:  # Define a volume for PostgreSQL data persistence
